export const UNIT_LIST_REQUEST = "UNIT_LIST_REQUEST";
export const UNIT_LIST_SUCCESS = "UNIT_LIST_SUCCESS";
export const UNIT_LIST_FAIL = "UNIT_LIST_FAIL";

export const UNIT_CHARGE_SAVE_REQUEST = "UNIT_CHARGE_SAVE_REQUEST";
export const UNIT_CHARGE_SAVE_SUCCESS = "UNIT_CHARGE_SAVE_SUCCESS";
export const UNIT_CHARGE_SAVE_FAIL = "UNIT_CHARGE_SAVE_FAIL";

export const UNIT_CHARGE_UPDATE_REQUEST = "UNIT_CHARGE_UPDATE_REQUEST";
export const UNIT_CHARGE_UPDATE_SUCCESS = "UNIT_CHARGE_UPDATE_SUCCESS";
export const UNIT_CHARGE_UPDATE_FAIL = "UNIT_CHARGE_UPDATE_FAIL";